import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { register } from "swiper/element/bundle";
// Import Swiper styles
import "swiper/swiper-bundle.css";
import "swiper/css/pagination";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  register();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
